version: "3.9"
services:
  sveltekit-app:
    build: .
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
    depends_on:
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN
